export const MAP_ENTER_PROGRESS = 0.28
export const MAP_REENTER_PROGRESS = 0.2
export const VEHICLE_ENTER_PROGRESS = 0.72
export const VEHICLE_REENTER_PROGRESS = 0.62

export const MAP_RETURN_SCROLL_PROGRESS = 0.33
export const VEHICLE_RETURN_SCROLL_PROGRESS = 0.76

export const MAP_PANEL_EXIT_PROGRESS = 0.985
export const VEHICLE_PANEL_EXIT_PROGRESS = 0.985
